package dev.ui.entity;

import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQuery;
import javax.persistence.PostPersist;
import javax.persistence.PrePersist;
import javax.persistence.Table;

//this is a simple entity class

@Entity
@NamedQuery(name = Staff.STAFFLIST_ORDER_BY_ID, query = "select s from Staff s order by s.staffName")
@Table(name="STAFF")
public class Staff implements Serializable{

	private static final long serialVersionUID = 1L;
	public static final String STAFFLIST_ORDER_BY_ID = "Staff.readAllOrderById";

	@Id	
	/*@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "Staff_Seq")
	@SequenceGenerator(name = "Staff_Seq",sequenceName = "STAFF_PK",allocationSize = 1)*/
	
	//by this strategy, PK is generated by sequence,inserted by trigger
	@Column(name="STAFF_ID")	
	private Integer staffId;
	
	@Column(name = "STAFF_NAME")
	private String	staffName;
	
	@Column(name= "DESIGNATION")
	private String designation;
	
	@Column(name = "DOJ")
	private LocalDate doj;
	
	@Column(name = "MOD_DATE")
	private LocalDate modDate;
	
	public Staff() {
		super();
	}
	
	public Integer getStaffId() {
		return staffId;
	}
	public void setStaffId(Integer staffId) {
	
		this.staffId = staffId;
	}	
	public String getStaffName() {
		return staffName;
	}
	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}
	public String getDesignation() {
		return designation;
	}
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	public LocalDate getDoj() {
		return doj;
	}
	public void setDoj(LocalDate doj) {
		this.doj = doj;
	}
	public LocalDate getModDate() {
		return modDate;
	}
	public void setModDate(LocalDate modDate) {
		this.modDate = modDate;
	}	
	
	@PrePersist
	public void stampAutoDate() {
		this.setModDate(LocalDate.now());
	}
	@PostPersist
	public void ackStaff() {
		System.out.println("One Staff Member created. ");
	}
	
}
